---
id: lgbtq
name: LGBTQ+ Friendliness
version: 1
author: Lumikeiju
icon: osmheart_lgbtq_slanted.svg

kinds: amenity

fields:
  lgbtq_friendliness:
    type: combo
    key: lgbtq
    label: LGBTQ+ Friendliness
    options:
      - only
      - primary
      - welcome
      - no
    labels:
      - only
      - primary
      - welcome
      - no
    customValues: false
