id: pride-map
name: Pride Map
version: 6
description: Adds LGBTQ+-friendliness tagging used by Pride Map
author: Lumikeiju
icon: osmheart_lgbtq_slanted_128.png
experimental: true
homepage: https://github.com/Lumikeiju/pride-map/tree/main/every-door-plugin
source: "https://github.com/Lumikeiju/pride-map/raw/refs/heads/main/every-door-plugin/pride-map.edp"
intro: This plugin adds LGBTQ+-friendliness tagging used by Pride Map. Thank you for contributing!

kinds:
  everything:
    update:
      amenity:
        except:
          - parking

presets:
  amenity:
    fields:
      - lgbtq_signage

fields:
  lgbtq_signage:
    label: LGBTQ+-friendliness signage
    key: "lgbtq:signed"
    type: combo
    customValues: false
    options:
      - yes
      - no
    labels:
      - Yes
      - No
  lgbtq_friendliness:
    label: LGBTQ+-friendliness level
    key: lgbtq
    type: combo
    customValues: false
    options:
      - only
      - primary
      - welcome
      - no
    labels:
      - Only
      - Primary
      - Welcome
      - No

modes:
  pride:
    icon: osmheart_lgbtq_slanted_bw_128.png
