name: ci 
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: zip -r every-door-plugin\pride-map.zip every-door-plugin\pride-map
      - run: mv every-door-plugin\pride-map.zip every-door-plugin\pride-map.edp
