name: main
on:
  push:
    branches:
      - main
    paths:
      - every-door-plugin/**
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run:
          |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Create EDP
        run:
          |
          cd every-door-plugin/pride-map
          zip -r ../../every-door-plugin/pride-map.edp . -x pride-map.edp

      - name: Commit and Push pride-map.edp
        run:
          |
          git add every-door-plugin/pride-map.edp
          git commit -m "Create pride-map.edp"
          git push
