name: main
on:
  push:
    branches:
      - main
    paths:
      - every-door-plugin/**
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run:
          |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Delete existing pride-map.edp
        run:
          |
          if [ -f every-door-plugin/pride-map.edp ]; then
            rm every-door-plugin/pride-map.edp
          fi

      - name: Create pride-map.zip archive
        run:
          |
          cd every-door-plugin/pride-map
          zip -r ../pride-map.zip .

      - name: Rename pride-map.zip to pride-map.edp
        run: mv every-door-plugin/pride-map.zip every-door-plugin/pride-map.edp
